language: node_js
node_js:
- '0.8'
env:
  global:
    secure: YICB7UhBQogay8WJPv38I6Ga0riqKUcYzouaeNhKZNEnaj4WO+ISTmYfTEBhsh5tIjx8z86rCSk7geqNnh1OEtOT0AJNoVSbSVPpsREv+vDTcj1vpwjZWCyLwJvbFgHBvLnYQsRCAwfDnxtw9MIxIUDsyh/GWBzkiBUxERedWlc=
install:
- git clone https://github.com/victornswd/intern-examples
- cd travis-ci-example
- npm install intern
script: node node_modules/intern/runner.js config=tests/intern
